name: Terraform Drift Detection

on:
  schedule:
    - cron: '0 2 * * *'  # Daily at 2 AM
  workflow_dispatch:  # Allow manual trigger

jobs:
  drift-detection:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      issues: write  # To create issues

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Azure Login with OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Terraform Init
        working-directory: infra/tf-app
        run: terraform init -backend-config="storage_account_name=${{ secrets.TF_STATE_STORAGE_ACCOUNT }}"

      - name: Terraform Plan for Drift
        id: plan
        working-directory: infra/tf-app
        run: |
          terraform plan -detailed-exitcode -no-color || true
          echo "::set-output name=exitcode::$?"

      - name: Create Issue if Drift Detected
        if: steps.plan.outputs.exitcode == '2'  # Exit code 2 means changes detected
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Terraform Drift Detected',
              body: 'Drift detected between Terraform config and Azure infrastructure. Run `terraform plan` for details.',
              labels: ['drift', 'terraform']
            });