name: Terraform Drift Detection

on:
  schedule:
    - cron: "0 6 * * *"  # Runs every day at 6 AM UTC

permissions:
  id-token: write
  contents: read

jobs:
  drift-detection:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform -chdir=infra/tf-app init

      - name: Terraform Plan (Check Drift)
        run: terraform -chdir=infra/tf-app plan -detailed-exitcode
