name: Terraform Drift Detection

on:
  schedule:
    - cron: '0 5 * * *'  # Every day at 5:00 UTC
  workflow_dispatch:     # Also allow manual run

permissions:
  id-token: write
  contents: read

jobs:
  drift-detection:
    name: Daily Terraform Plan Check
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Azure Login via OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform -chdir=infra/tf-app init

      - name: Terraform Plan
        run: terraform -chdir=infra/tf-app plan
