name: Terraform Static Tests

on:
  push:
    branches: [ master, develop ]
    paths:
      - 'infra/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'infra/**'

env:
  TF_VERSION: "1.5.0"
  TFLINT_VERSION: "0.47.0"

jobs:
  static-tests:
    name: Static Code Analysis
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Setup TFLint
      uses: terraform-linters/setup-tflint@v4
      with:
        tflint_version: v${{ env.TFLINT_VERSION }}

    - name: TFLint
      working-directory: ./infra/tf-app
      run: tflint --init && tflint

    - name: Terraform Format Check
      working-directory: ./infra/tf-app
      run: terraform fmt -check -recursive

    - name: Terraform Validate
      working-directory: ./infra/tf-app
      run: terraform init -backend=false && terraform validate 