name: Terraform Static Tests

on:
  push:
    branches:
      - '**'

permissions:
  id-token: write
  contents: read

jobs:
  static-check:
    name: Static Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Format Check
        run: terraform -chdir=infra/tf-app fmt -check -diff

      - name: Install tflint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

      - name: Run tflint
        run: |
          cd infra/tf-app
          tflint --init
          tflint
