name: Static Terraform Checks

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main

jobs:
  static-analysis:
    name: Static Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Terraform Format Check
        working-directory: infra/tf-app
        run: terraform fmt -check -recursive

      - name: Install tflint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

      - name: Run tflint
        working-directory: infra/tf-app
        run: tflint --recursive

        