name: Terraform Static Analysis

on:
  push:
    branches:
      - "**"

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Format Check
        run: terraform -chdir=infra/tf-app fmt -check

      - name: Install TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: v0.50.3

      - name: Run TFLint
        run: tflint -c infra/tf-app/.tflint.hcl infra/tf-app
