name: Terraform Static Analysis

on:
  push:
    branches:
      - "**"

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform -chdir=infra/tf-app init -backend=false -upgrade

      - name: Terraform Format Check
        run: terraform -chdir=infra/tf-app fmt -check

      - name: Terraform Validate
        run: terraform -chdir=infra/tf-app validate

      - name: Install Checkov
        run: pip install checkov

      - name: Run Checkov
        run: checkov -d infra/tf-app
