name: Terraform Drift Detection

on:
  schedule:
    - cron: "0 6 * * *"  # Runs daily at 6 AM UTC
  workflow_dispatch:      # Allows manual trigger

permissions:
  id-token: write
  contents: write
  issues: write

jobs:
  drift-detection:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform -chdir=infra/tf-app init

      - name: Terraform Plan (Detect Drift)
        id: plan
        run: terraform -chdir=infra/tf-app plan -detailed-exitcode || echo "exit_code=$?" >> $GITHUB_ENV

      - name: Create Drift Issue
        if: env.exit_code == '2'
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: "⚠️ Drift Detected in Terraform Infrastructure"
          content-filepath: .github/drift-message.md
          labels: drift

      - name: Close Drift Issue if No Drift
        if: env.exit_code != '2'
        run: |
          gh issue list --label drift --state open --json number --jq '.[].number' | while read issue; do
            gh issue close "$issue" -c "✅ No drift detected in latest run."
          done
